### ISSUE TITLE
默认选择当前月份时，账单统计页面没能直接展示出当前月份的统计数据（当前月已有记账信息）

### ISSUE THREAD

**Issue by here-tunan** [here-tunan/my-life#1]
![image](https://github.com/here-tunan/my-life/assets/40956738/97399cca-b57c-4618-9f91-5660b85b87b1)

**Comment by xiburg** [comment]
https://github.com/xiburg/my-life.git

**Comment by xiburg** [comment]
fixed

**Comment by xiburg** [comment]
fix the issue by this [pr](https://github.com/here-tunan/my-life/pulls)

**Comment by here-tunan** [comment]
It's done
